print("=== The Ultimate Wacky Recipe maker ===")
food = input("Name a food: ")
plant = input("Name a type of plant: ")
cooking = input("Name a method of cooking: ")
burned = input("What word describes burned food?: ")
item = input("Name a household item: ")
print(f'you can {cooking} {food} with {burned} {plant} on a bed of {item}')
