userName = input('What is your name?')
print('Hello, ' + userName)
favFood = input('What is your favorite food?')
print('I like ' + favFood + ' too!')
favMusic = input('What is your favorite music?')
print(favMusic)
print('is a good choice!')
address = input('Where do you live?')
print(address + ' is a nice place to live!')
print("So, your name is " + userName + ", your favorite food is " + favFood + ", your favorite music is " + favMusic + ", and you live in " + address + "." )
print(userName + ", you're awesome!"	)